import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Microphone, Camera, House, Bag, ChatCircleDots, User, Globe, Bell, Package, ChartBar, ArrowLeft, ArrowRight, CaretRight, Check, Plus, PencilSimple, Stop, UploadSimple, Sun, Crosshair, Image as ImageIcon, SignOut, Question, X, CheckCircle, Eye, Sparkle } from '@phosphor-icons/react';
import { MobileScroll, KeyboardInput, KeyboardTextarea, useKeyboard, useKeyboardInsets, BottomSheet } from './mobile';
import '@fontsource/nunito-sans/400.css';
import '@fontsource/nunito-sans/600.css';
import '@fontsource/nunito-sans/700.css';
import '@fontsource/nunito-sans/800.css';
import './prototype.css';

type Product = {name:string;category:string;material:string;size:string;craft:string;description:string;minimum:string;price:string;quantity:string;delivery:string;photo:string;status:string};
const sample:Product={name:'Handwoven Storage Basket',category:'Home & Living',material:'Natural fibre',size:'30 × 25 cm',craft:'Handwoven',description:'A versatile woven basket with two easy-carry handles for everyday storage.',minimum:'800',price:'950',quantity:'12',delivery:'7 days',photo:'/assets/basket.png',status:'Draft'};
const blank:Product={name:'',category:'',material:'',size:'',craft:'',description:'',minimum:'',price:'',quantity:'',delivery:'',photo:'',status:'Draft'};
const navItems=[['Home',House],['Products',Bag],['Enquiries',ChatCircleDots],['Profile',User]] as const;
function Field({label,value,onChange,type='text',placeholder=''}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string}) {return <label className="field">{label}<KeyboardInput type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function Button({children,onClick,secondary=false,disabled=false}:{children:ReactNode;onClick:()=>void;secondary?:boolean;disabled?:boolean}) {return <button className={secondary?'button secondary':'button primary'} disabled={disabled} onClick={onClick}>{children}</button>}
function Brand(){return <div className="brand"><img src="/assets/diya.png" alt="Karigar Kart diya"/><div><strong>KARIGAR <span>KART</span></strong><small>HANDMADE. TRUSTED. DELIVERED.</small></div></div>}
export default function Prototype(){
 const [page,setPage]=useState('Home'); const [history,setHistory]=useState<string[]>([]); const [sheet,setSheet]=useState(''); const [notice,setNotice]=useState('');
 const [product,setProduct]=useState<Product>({...sample}); const [products,setProducts]=useState<Product[]>([{...sample,status:'Live'},{...sample,name:'Woven Basket — Small',price:'650',status:'Out of Stock',quantity:'0'},{...sample}]);
 const [editingIndex,setEditingIndex]=useState<number|null>(null); const [filter,setFilter]=useState('All'); const [recording,setRecording]=useState(false); const [seconds,setSeconds]=useState(0); const [typed,setTyped]=useState(false); const [voiceText,setVoiceText]=useState(''); const [busy,setBusy]=useState(false); const [enhanced,setEnhanced]=useState(false); const [photoTab,setPhotoTab]=useState('After');
 const [responded,setResponded]=useState(false); const [requestStatus,setRequestStatus]=useState('New Request'); const [reply,setReply]=useState({quantity:'20',price:'900',timeline:'10 days',custom:'Yes',charges:'0',message:''});
 const [profile,setProfile]=useState({name:'Sunita',business:'Sunita Handcrafts',location:'Bhubaneswar, Odisha',craft:'Basket weaving',contact:'sunita@example.com'});
 const [auth,setAuth]=useState({name:'',email:'',password:'',confirm:'',terms:false}); const [error,setError]=useState(''); const file=useRef<HTMLInputElement>(null);const keyboard=useKeyboard(); const {bottomInset}=useKeyboardInsets();
 const go=(p:string)=>{keyboard.hide();setError('');setRecording(false);setHistory(h=>[...h,page]);setPage(p)}; const back=()=>{keyboard.hide();setPage(history.at(-1)||'Home');setHistory(h=>h.slice(0,-1));setError('')};
 const tab=(p:string)=>{keyboard.hide();setHistory([]);setPage(p);setError('')}; const update=(k:keyof Product,v:string)=>setProduct(p=>({...p,[k]:v}));
 const tell=(message:string)=>{keyboard.hide();setNotice(message);setTimeout(()=>setNotice(''),3500)};
 useEffect(()=>{if(!recording)return;const t=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(t)},[recording]);
 const demoVoice=()=>{setRecording(false);setBusy(true);setTimeout(()=>{setProduct({...sample,material:'',craft:'',photo:'',minimum:'',price:'',quantity:'',delivery:''});setBusy(false);go('Check Details')},900)};
 const start=()=>{setEditingIndex(null);setProduct({...blank});setVoiceText('');setTyped(false);setEnhanced(false);setSeconds(0);go('Tell Your Story')};
 const save=(status:string)=>{const saved={...product,status};setProducts(ps=>editingIndex===null?[saved,...ps]:ps.map((p,i)=>i===editingIndex?saved:p));setEditingIndex(null);setProduct(saved);if(status==='Live')go('Published');else {tab('Products');tell('Draft saved. Continue whenever you are ready.')}};
 const workflow=['Tell Your Story','Check Details','Missing Detail','Add Photos','Photo Review','Listing Preview','Smart Pricing','Final Review']; const stage=workflow.includes(page)? page==='Tell Your Story'||page==='Check Details'||page==='Missing Detail'?1:page==='Add Photos'||page==='Photo Review'?2:page==='Listing Preview'?3:4:0;
 const authPage=['Welcome','Login','Sign Up','Forgot Password'].includes(page); const navVisible=!authPage&&!stage&&page!=='Published';
 const draft=products.find(p=>p.status==='Draft');
 const detailFields=()=> <div className="details">{(['name','category','material','size','craft'] as const).map(k=><Field key={k} label={({name:'Product Name',category:'Category',material:'Material',size:'Size',craft:'Craft / Technique'})[k]} value={product[k]} onChange={v=>update(k,v)} placeholder="Not specified"/>)}</div>;
 const mini=(p:Product)=> <div className="product-summary"><img src={p.photo||'/assets/basket.png'} alt={p.name||'Product'}/><div><h3>{p.name||'Untitled product'}</h3><p>{p.category||'Category not specified'}</p>{p.price&&<strong>₹{p.price}</strong>}</div></div>;
 const content=()=>{switch(page){
 case 'Home':return <><div className="home-greeting"><h1>Hello, {profile.name}</h1><p>Keep creating. Handmade changes lives.</p></div><section className="voice-hero"><div className="eyebrow">SPEAK FIRST</div><h2>Create New Product Listing</h2><p>Turn your craft into opportunity.</p><div className="voice-actions"><button className="voice-circle" onClick={start}><Microphone size={58} weight="light"/><span>Start Listing</span></button><span className="camera-bubble"><Camera size={29}/></span></div><p className="hero-bottom">Speak about your product. Add a photo.</p></section><div className="shortcuts">{[['My Products',Bag,'Products'],['Buyer Enquiries',ChatCircleDots,'Enquiries'],['Orders / Requests',Package,'Requests'],['Insights',ChartBar,'Insights']].map(([label,Icon,p])=><button key={String(p)} onClick={()=>go(String(p))}>{typeof Icon!=='string'&&<Icon size={31} weight="light"/>}<span>{String(label)}</span></button>)}</div>{draft&&<section className="continue"><h2>Continue where you left off</h2><button className="draft-card" onClick={()=>{setEditingIndex(products.indexOf(draft));setProduct({...draft});go('Check Details')}}><img src={draft.photo} alt="Woven basket draft"/><div><small>DRAFT</small><h3>{draft.name}</h3><p>Finish your listing and share your craft with the world.</p></div><CaretRight size={20}/></button></section>}</>;
 case 'Tell Your Story':return <><h1>Tell us about your product</h1><p>Its name, size and what makes it special.</p><div className="record-area"><button className={'voice-circle '+(recording?'recording':'')} aria-label={recording?'Stop recording':'Tap to Speak'} onClick={()=>{if(recording)demoVoice();else {setRecording(true);setSeconds(0)}}}>{recording?<Stop size={44}/>:<Microphone size={54}/>}<span>{recording?'Stop':'Tap to Speak'}</span></button><p>{recording?`0:${String(seconds).padStart(2,'0')} · Recording demo`:'Voice interaction preview'}</p></div>{busy?<p role="status">Preparing your product listing…</p>:<><button className="text-button" onClick={()=>setTyped(!typed)}>Type Instead</button>{typed&&<><label className="field">Product description<KeyboardTextarea value={voiceText} onChange={e=>setVoiceText(e.target.value)} placeholder="Describe your product in your own words"/></label><Button disabled={!voiceText.trim()} onClick={()=>{setProduct({...blank,description:voiceText});go('Check Details')}}>Use Description <ArrowRight/></Button></>}<div className="note">Try the voice flow with a sample basket description.</div><Button secondary onClick={demoVoice}>Use Sample Description</Button></>}</>;
 case 'Check Details':return <><h1>Does this look right?</h1><p>Check the details before continuing. Only keep information you can confirm.</p>{detailFields()}<label className="field">Short Description<KeyboardTextarea value={product.description} onChange={e=>update('description',e.target.value)}/></label><Button disabled={!product.name.trim()} onClick={()=>go(!product.material?'Missing Detail':'Add Photos')}>Confirm Details <ArrowRight/></Button><Button secondary onClick={()=>save('Draft')}>Save as Draft</Button></>;
 case 'Missing Detail':return <><div className="question-icon"><Question size={48}/></div><h1>What material is it made from?</h1><p>Choose one, type your answer, or leave it unspecified.</p><div className="choices">{['Natural fibre','Bamboo','Cotton','Clay'].map(v=><button className={product.material===v?'selected':''} onClick={()=>update('material',v)} key={v}>{v}</button>)}</div><Field label="Material" value={product.material} onChange={v=>update('material',v)}/><Button secondary onClick={()=>tell('Voice answer preview: choose an option or type your answer.') }><Microphone/> Answer by Voice</Button><Button onClick={()=>go('Add Photos')}>Continue <ArrowRight/></Button><button className="text-button" onClick={()=>{update('material','');go('Add Photos')}}>Leave Unspecified</button></>;
 case 'Add Photos':return <><h1>Let your product shine</h1><p>Add a clear photo of the actual product.</p><div className="upload-box"><Camera size={54} weight="light"/><h2>Add product photos</h2><Button onClick={()=>{file.current?.setAttribute('capture','environment');file.current?.click()}}><Camera/> Take Photo</Button><Button secondary onClick={()=>{file.current?.removeAttribute('capture');file.current?.click()}}><UploadSimple/> Upload Photo</Button></div><div className="photo-tips"><span><Sun/>Good lighting</span><span><Crosshair/>Keep centered</span><span><ImageIcon/>Clean background</span></div><Button secondary onClick={()=>{update('photo','/assets/basket.png');setEnhanced(false);go('Photo Review')}}>Use Sample Photo</Button><p className="muted">Your product's colour, shape and craft stay yours.</p></>;
 case 'Photo Review':return <><h1>A clearer first impression</h1><p>Keep the product true to life.</p>{enhanced&&<div className="segmented">{['Before','After'].map(v=><button className={photoTab===v?'active':''} onClick={()=>setPhotoTab(v)} key={v}>{v}</button>)}</div>}<img className={'large-product '+(enhanced&&photoTab==='After'?'enhanced':'')} src={product.photo} alt={`${photoTab} product preview`}/>{busy?<div className="note" role="status">Preparing your product photo…</div>:!enhanced?<Button onClick={()=>{setBusy(true);setTimeout(()=>{setEnhanced(true);setPhotoTab('After');setBusy(false)},800)}}><Sparkle/> Enhance Photo</Button>:<div className="note"><CheckCircle/> Lighting preview applied. Review before using.</div>}<p className="muted">Prototype: a subtle brightness preview. Background removal and sharpening need the image service.</p><Button onClick={()=>go('Listing Preview')}>Use This Photo <ArrowRight/></Button><Button secondary onClick={()=>go('Add Photos')}>Choose Another Photo</Button></>;
 case 'Listing Preview':return <><h1>Your listing, coming together</h1><img className="large-product" src={product.photo} alt={product.name}/><h2>{product.name}</h2><p>{product.description||'Add a short description before publishing.'}</p><div className="attributes"><span>{product.category||'Category unspecified'}</span><span>{product.material||'Material unspecified'}</span><span>{product.size||'Size unspecified'}</span>{product.craft&&<span>{product.craft}</span>}</div><p className="muted">Tags: {product.category?product.category.toLowerCase():'not specified'}</p><Button secondary onClick={()=>go('Check Details')}><PencilSimple/> Edit Details</Button><Button onClick={()=>go('Smart Pricing')}>Continue to Pricing <ArrowRight/></Button></>;
 case 'Smart Pricing':return <><h1>You choose your price</h1><p>What is the minimum price you are willing to accept?</p><Field label="Minimum Price (₹)" value={product.minimum} onChange={v=>update('minimum',v)} type="number" placeholder="e.g. 800"/><section className="pricing-card"><small>SUGGESTED PRICE RANGE</small><h1>₹850 – ₹1,050</h1><p>Based on similar products and current market prices.</p><span className="pill">Illustrative sample range</span></section><Field label="Selected Selling Price (₹)" value={product.price} onChange={v=>update('price',v)} type="number" placeholder="Choose your price"/><div className="choices prices">{['850','950','1050'].map(v=><button disabled={+v<+product.minimum} className={product.price===v?'selected':''} onClick={()=>update('price',v)} key={v}>₹{v}</button>)}</div>{+product.minimum>1050&&<p className="note">The sample range is below your minimum. Choose a price that works for you.</p>}{product.price&&+product.price<+product.minimum&&<p className="error">Selling price must meet your minimum.</p>}<p className="muted">The recommendation is a guide. The final price is always yours.</p><Button disabled={!product.minimum||+product.minimum<=0||!product.price||+product.price<+product.minimum} onClick={()=>go('Final Review')}>Review Listing <ArrowRight/></Button></>;
 case 'Final Review':return <><h1>Ready to share your craft?</h1>{mini(product)}<div className="info-card"><h3>Product Details</h3><p>{product.description}</p><p>{[product.material,product.size,product.craft].filter(Boolean).join(' · ')||'Additional attributes unspecified'}</p><button className="text-button" onClick={()=>go('Check Details')}>Edit Details</button></div><div className="price-row"><span>Selling Price</span><strong>₹{product.price}</strong><button aria-label="Edit price" className="icon-button" onClick={()=>go('Smart Pricing')}><PencilSimple/></button></div><Field label="Available Quantity" value={product.quantity} type="number" onChange={v=>update('quantity',v)} placeholder="e.g. 12"/><Field label="Delivery Estimate" value={product.delivery} onChange={v=>update('delivery',v)} placeholder="e.g. 7–10 days"/><Button disabled={!product.name||!product.photo||+product.price<=0||+product.price<+product.minimum||!product.quantity||+product.quantity<=0||!Number.isInteger(+product.quantity)||!product.delivery.trim()} onClick={()=>save('Live')}>Publish Product <ArrowRight/></Button><Button secondary onClick={()=>save('Draft')}>Save as Draft</Button><p className="muted">Publishing updates this prototype's sample catalogue.</p></>;
 case 'Published':return <div className="success"><CheckCircle size={80} weight="light"/><h1>Your product is live!</h1><p>A new beginning for your craft.</p>{mini(product)}<Button onClick={()=>tab('Products')}>View My Products</Button><Button secondary onClick={()=>tab('Home')}>Back to Home</Button></div>;
 case 'Products':return <><div className="heading-row"><div><h1>My Products</h1><p>Your craft, in one place.</p></div><button className="icon-button amber" aria-label="Create product" onClick={start}><Plus/></button></div><div className="segmented filters">{['All','Live','Draft','Out of Stock'].map(v=><button key={v} className={filter===v?'active':''} onClick={()=>setFilter(v)}>{v}</button>)}</div><div className="product-grid">{products.filter(p=>filter==='All'||p.status===filter).map((p,i)=><button className="product-card" key={i} onClick={()=>{setEditingIndex(products.indexOf(p));setProduct({...p});go('Product Detail')}}><div className="product-media">{p.photo?<img src={p.photo} alt={p.name||'Draft'}/>:<span><ImageIcon size={35}/>Photo not added</span>}</div><div><span className="pill">{p.status}</span><h3>{p.name||'Untitled product'}</h3><strong>{p.price?'₹'+p.price:'Price not set'}</strong><p>{p.quantity||0} available</p></div></button>)}</div>{!products.some(p=>filter==='All'||p.status===filter)&&<p>No products here yet.</p>}</>;
 case 'Product Detail':return <>{product.photo?<img className="large-product" src={product.photo} alt={product.name}/>:<div className="upload-box"><ImageIcon size={40}/><p>Photo not added yet</p></div>}<span className="pill">{product.status}</span><h1>{product.name||'Untitled product'}</h1><h2>₹{product.price||'—'}</h2><p>{product.description}</p><div className="info-card"><p>{product.quantity||0} available</p><p>Delivery: {product.delivery||'Not set'}</p></div><Button onClick={()=>go('Check Details')}><PencilSimple/> Edit Listing</Button>{product.status!=='Draft'&&<Button secondary onClick={()=>{const status=product.status==='Out of Stock'?'Live':'Out of Stock';setProducts(ps=>ps.map(p=>p.name===product.name?{...p,status}:p));update('status',status);tell('Availability updated')}}>{product.status==='Out of Stock'?'Mark Available':'Mark Out of Stock'}</Button>}</>;
 case 'Enquiries':return <><h1>Buyer Enquiries</h1><p>New connections for your craft.</p><span className="pill">Sample enquiries</span><section className="enquiry-card"><div className="heading-row"><h2>The Earth Store</h2><span className="pill">{responded?'Replied':'New'}</span></div><p>Business buyer · New Delhi</p><div className="product-summary"><img src="/assets/basket.png" alt="Woven basket"/><div><h3>Handwoven Storage Basket</h3><p>20 pieces required</p></div></div><div className="facts"><span>Required by</span><strong>25 Sep 2026</strong><span>Customisation</span><strong>Natural colour, gift tags</strong></div><Button onClick={()=>go('View Request')}>View Request <ArrowRight/></Button></section></>;
 case 'View Request':return <><h1>The Earth Store</h1><p>Business buyer · New Delhi</p>{mini({...sample})}<div className="info-card facts"><span>Quantity Required</span><strong>20 pieces</strong><span>Requested Date</span><strong>25 Sep 2026</strong><span>Customisation</span><strong>Natural colour, gift tags</strong><span>Location</span><strong>New Delhi</strong></div>{responded&&<div className="note"><CheckCircle/> Your response is saved in this demo.</div>}<Button onClick={()=>go('Respond')}>{responded?'Edit Response':'Respond'} <ArrowRight/></Button></>;
 case 'Respond':return <><h1>Make it clear and simple</h1><p>Your response to The Earth Store.</p>{[['quantity','Available Quantity'],['price','Bulk Price per Piece (₹)'],['timeline','Delivery Timeline'],['charges','Additional Charges (₹)']].map(([k,label])=><Field key={k} label={label} value={reply[k as keyof typeof reply]} type={['quantity','price','charges'].includes(k)?'number':'text'} onChange={v=>setReply(r=>({...r,[k]:v}))}/>)}<label className="field">Customisation Possible<select value={reply.custom} onChange={e=>setReply(r=>({...r,custom:e.target.value}))}><option>Yes</option><option>No</option><option>Partly</option></select></label><label className="field">Optional Message<KeyboardTextarea value={reply.message} onChange={e=>setReply(r=>({...r,message:e.target.value}))} placeholder="Anything else the buyer should know?"/></label><Button disabled={+reply.quantity<=0||+reply.price<=0||+reply.charges<0||!reply.timeline.trim()} onClick={()=>{setResponded(true);setRequestStatus('Discussion');go('View Request');tell('Response saved in the prototype.')}}>Send Response <ArrowRight/></Button></>;
 case 'Requests':return <><h1>Orders / Requests</h1><p>Keep track of buyer interest.</p><span className="pill">Sample request</span><button className="enquiry-card request-link" onClick={()=>go('Request Detail')}><div className="heading-row"><h2>The Earth Store</h2><CaretRight/></div><span className="pill">{requestStatus}</span><p>Handwoven Storage Basket</p><div className="facts"><span>Quantity</span><strong>20 pieces</strong><span>Agreed price</span><strong>{requestStatus==='New Request'?'Not agreed':`₹${reply.price} / piece`}</strong><span>Required date</span><strong>25 Sep 2026</strong></div></button></>;
 case 'Request Detail':return <><h1>Request Details</h1><span className="pill">{requestStatus}</span>{mini({...sample})}<div className="info-card"><h3>The Earth Store</h3><p>20 pieces · New Delhi</p><p>Required by 25 Sep 2026</p><p>{requestStatus==='New Request'?'Price not agreed':`Agreed price: ₹${reply.price} per piece`}</p></div><p>This tracks order intent. Confirm arrangements with the buyer.</p>{requestStatus==='New Request'?<Button onClick={()=>go('Respond')}>Discuss Request</Button>:requestStatus==='Discussion'?<Button onClick={()=>{setRequestStatus('Accepted');tell('Request accepted in this demo.')}}>Accept Request</Button>:requestStatus==='Accepted'?<Button onClick={()=>{setRequestStatus('Completed');tell('Request marked completed.')}}>Mark Completed</Button>:<div className="note"><CheckCircle/> Request completed</div>}</>;
 case 'Insights':return <><h1>A little insight, a new idea</h1><p>This week · 7–13 Sep 2026</p><span className="pill">Illustrative activity</span><div className="stats"><div><Eye/><p>Product Views</p><h1>248</h1></div><div><ChatCircleDots/><p>Buyer Enquiries</p><h1>12</h1></div></div><section className="info-card"><h2>Most Viewed Product</h2>{mini(sample)}<p>86 views this week</p></section><section className="info-card"><h2>Approximate Price Trend</h2><div className="trend-values"><span>Aug<br/><strong>₹900</strong></span><ArrowRight/><span>Sep<br/><strong>₹950</strong></span></div><p>Sample prices for similar baskets</p></section><div className="note">Your handwoven baskets received the most buyer interest this week.</div><Button onClick={()=>tab('Products')}>View My Products</Button></>;
 case 'Profile':return <><div className="profile-top"><img src="/assets/avatar.png" alt="Sunita profile"/><h1>{profile.name}</h1><p>{profile.business}</p></div>{Object.entries({name:'Name',business:'Business / Artisan Name',location:'Location',craft:'Craft Category',contact:'Contact'}).map(([k,label])=><Field key={k} label={label} value={profile[k as keyof typeof profile]} onChange={v=>setProfile(p=>({...p,[k]:v}))}/>)}<label className="field">Preferred Language<select disabled><option>English</option></select></label><Button onClick={()=>tell('Profile updated for this session.')}><Check/> Save Profile</Button><button className="list-row" onClick={()=>setSheet('Account Settings')}>Account Settings<CaretRight/></button><button className="list-row" onClick={()=>setSheet('Help')}>Help<Question/></button><button className="list-row" onClick={()=>go('Welcome')}>Logout<SignOut/></button></>;
 case 'Welcome':return <div className="welcome"><img className="welcome-logo" src="/assets/diya.png" alt="Karigar Kart diya"/><h1>KARIGAR KART</h1><small>HANDMADE. TRUSTED. DELIVERED.</small><h2>Your craft.<br/>A world of possibilities.</h2><p>Empowering artisans, celebrating craftsmanship.</p><Button onClick={()=>go('Sign Up')}>Get Started <ArrowRight/></Button><p>Already have an account?</p><button className="text-button" onClick={()=>go('Login')}>Login</button></div>;
 case 'Login':case 'Sign Up':return <><div className="auth-heading"><img src="/assets/diya.png" alt="Diya"/><h1>{page==='Login'?'Welcome Back':'Create Account'}</h1><p>{page==='Login'?'Login to continue to Karigar Kart':'Join the Karigar Kart community'}</p></div>{page==='Sign Up'&&<Field label="Full Name" value={auth.name} onChange={v=>setAuth(a=>({...a,name:v}))}/>}<Field label="Email / Mobile Number" value={auth.email} onChange={v=>setAuth(a=>({...a,email:v}))}/><Field label="Password" type="password" value={auth.password} onChange={v=>setAuth(a=>({...a,password:v}))}/>{page==='Sign Up'?<><Field label="Confirm Password" type="password" value={auth.confirm} onChange={v=>setAuth(a=>({...a,confirm:v}))}/><label className="checkbox"><input type="checkbox" checked={auth.terms} onChange={e=>setAuth(a=>({...a,terms:e.target.checked}))}/>I agree to the <button className="text-button" onClick={()=>setSheet('Terms & Conditions')}>Terms & Conditions</button></label></>:<button className="text-button align-right" onClick={()=>go('Forgot Password')}>Forgot Password?</button>}{error&&<p role="alert" className="error">{error}</p>}<Button onClick={()=>{if(!auth.email||!auth.password||(page==='Sign Up'&&(!auth.name||!auth.terms||auth.password!==auth.confirm))){setError('Complete all fields, match passwords and accept terms.');return;}tab('Home');tell('Demo account opened. No credentials are sent or stored.')}}>{page==='Login'?'Login':'Create Account'}</Button><p className="muted">Preview only. Use sample details.</p><button className="text-button" onClick={()=>go(page==='Login'?'Sign Up':'Login')}>{page==='Login'?'Create account':'Already have an account? Login'}</button></>;
 case 'Forgot Password':return <><h1>Forgot your password?</h1><p>Enter your email or mobile number.</p><Field label="Email / Mobile Number" value={auth.email} onChange={v=>setAuth(a=>({...a,email:v}))}/><Button disabled={!auth.email.trim()} onClick={()=>tell('Recovery preview complete. No email or SMS was sent.')}>Send Reset Instructions</Button></>;
 default:return null;
 }};
 return <div className="kk-app"><header className="kk-header">{page==='Home'?<><Brand/><div className="header-actions"><button className="icon-button avatar-button" aria-label="Open profile" onClick={()=>tab('Profile')}><img src="/assets/avatar.png" alt=""/></button><button className="icon-button" aria-label="Notifications" onClick={()=>setSheet('Notifications')}><Bell size={22}/><i/></button><button className="icon-button" aria-label="Language" onClick={()=>setSheet('Language')}><Globe size={23}/></button></div></>:<><button className="icon-button" aria-label="Back" onClick={back}><ArrowLeft size={23}/></button><strong>{stage?'Create Listing':authPage?'Karigar Kart':page}</strong><span className="header-count">{stage?`${stage} of 4`:''}</span></>}</header>{stage>0&&<div className="stepper" aria-label={`Step ${stage} of 4`}>{[1,2,3,4].map(n=><span key={n} className={n<=stage?'done':''}/>)}</div>}<MobileScroll key={page} className="kk-scroll"><main className={'kk-content '+(page==='Home'?'home-content':'')}>{content()}</main></MobileScroll>{navVisible&&<nav className="bottom-nav" aria-label="Main navigation" style={{bottom:bottomInset}}>{navItems.map(([name,Icon])=><button className={page===name?'active':''} key={name} onClick={()=>tab(name)}><Icon size={27} weight={page===name?'fill':'light'}/><span>{name}</span></button>)}</nav>}{notice&&<div className="toast" role="status" style={{bottom:bottomInset+88}}><CheckCircle size={22}/>{notice}</div>}<input ref={file} type="file" accept="image/*" hidden onChange={e=>{const f=e.target.files?.[0];if(f){if(!f.type.startsWith('image/')){tell('Please choose an image.');return;}update('photo',URL.createObjectURL(f));setEnhanced(false);go('Photo Review')}}}/><BottomSheet open={!!sheet} onOpenChange={open=>!open&&setSheet('')} title={sheet}><div className="kk-sheet">{sheet==='Notifications'?<><h3>One new buyer enquiry</h3><p>The Earth Store is interested in 20 baskets.</p><Button onClick={()=>{setSheet('');go('Enquiries')}}>View Enquiries</Button></>:sheet==='Language'?<><p>English is selected.</p><p>Regional languages will be available in a future release.</p></>:sheet==='Help'?<><h3>From your voice to your first listing</h3><p>Speak or type about your product, add a photo, review the details, set your price and publish.</p><p>Save a draft at any time from the details or final review screen.</p></>:sheet==='Account Settings'?<><p>This interactive demo uses sample data. Changes last until the page is refreshed.</p><Button secondary onClick={()=>{setSheet('');go('Forgot Password')}}>Password Recovery</Button></>:<p>Prototype terms preview only. A production service will provide its full terms and privacy policy before registration.</p>}<Button secondary onClick={()=>setSheet('')}>Close</Button></div></BottomSheet></div>
}
